<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="34.2.6" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="34.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeaveManagementPortal.BusinessLayer\LeaveManagementPortal.BusinessLayer.csproj" />
    <ProjectReference Include="..\LeaveManagementPortal.Common\LeaveManagementPortal.Common.csproj" />
    <ProjectReference Include="..\LeaveManagementPortal.Model\LeaveManagementPortal.Model.csproj" />
  </ItemGroup>

</Project>
